function A = A_GRAC_leg(in1,in2)
%A_GRAC_LEG
%    A = A_GRAC_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Nov-2019 15:56:26

I3 = in2(8,:);
I4 = in2(10,:);
l3 = in2(13,:);
lc3 = in2(16,:);
lc4 = in2(17,:);
m1 = in2(3,:);
m2 = in2(5,:);
m3 = in2(7,:);
m4 = in2(9,:);
tha = in1(3,:);
thh = in2(2,:);
thk = in1(2,:);
t2 = lc3.^2;
t3 = lc4.^2;
t4 = -thk;
t5 = t4+thh;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+tha;
t9 = cos(t8);
t10 = sin(t8);
t11 = l3.*t6;
t12 = l3.*t7;
t14 = lc3.*m3.*t7;
t13 = lc4.*t9;
t15 = lc4.*t10;
t16 = t12.*2.0;
t19 = -t14;
t17 = t15.*2.0;
t18 = m4.*t15;
t20 = t11+t13;
t21 = t12+t15;
t22 = t16+t17;
t25 = t13.*t20.*2.0;
t26 = t17.*t21;
t23 = (m4.*t22)./2.0;
t28 = t25+t26;
t24 = -t23;
t29 = (m4.*t28)./2.0;
t27 = t19+t24;
t30 = -t29;
A = reshape([m1+m2+m3+m4,t27,t18,t27,I3+(m3.*(t2.*t6.^2.*2.0+t2.*t7.^2.*2.0))./2.0+(m4.*(t20.^2.*2.0+t21.^2.*2.0))./2.0,t30,t18,t30,I4+(m4.*(t3.*t9.^2.*2.0+t3.*t10.^2.*2.0))./2.0],[3,3]);
