function C = C_GRAC_leg(in1,in2,in3)
%C_GRAC_LEG
%    C = C_GRAC_LEG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Nov-2019 15:56:28

y = in1(1,:);
C = y;
