function dC = dC_GRAC_leg(in1,in2,in3)
%DC_GRAC_LEG
%    DC = DC_GRAC_LEG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Nov-2019 15:56:28

dy = in1(4,:);
dC = dy;
