function dre = velocity_foot(in1,in2)
%VELOCITY_FOOT
%    DRE = VELOCITY_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-Nov-2019 18:59:20

dtha = in1(6,:);
dthk = in1(5,:);
dy = in1(4,:);
l3 = in2(13,:);
l4 = in2(14,:);
tha = in1(3,:);
thh = in2(2,:);
thk = in1(2,:);
t2 = tha+thh-thk;
t3 = cos(t2);
t4 = thh-thk;
t5 = sin(t2);
dre = [-dthk.*(l4.*t3+l3.*cos(t4))+dtha.*l4.*t3;dy-dthk.*(l4.*t5+l3.*sin(t4))+dtha.*l4.*t5;0.0];
