function b = b_GRAC_leg(in1,in2,Fy,in4)
%B_GRAC_LEG
%    B = B_GRAC_LEG(IN1,IN2,FY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Nov-2019 13:01:30

dtha = in1(6,:);
dthk = in1(5,:);
dy = in1(4,:);
g = in4(19,:);
l3 = in4(13,:);
l4 = in4(14,:);
lc3 = in4(16,:);
lc4 = in4(17,:);
m1 = in4(3,:);
m2 = in4(5,:);
m3 = in4(7,:);
m4 = in4(9,:);
taua = in2(2,:);
tauk = in2(1,:);
tha = in1(3,:);
thh = in4(2,:);
thk = in1(2,:);
t2 = tha+thh-thk;
t3 = cos(t2);
t4 = thh-thk;
t5 = cos(t4);
t6 = lc4.*t3;
t7 = l3.*t5;
t8 = t6+t7;
t9 = sin(t2);
t10 = dthk.*t8;
t21 = dtha.*lc4.*t3;
t11 = t10-t21;
t12 = lc4.*t9;
t13 = sin(t4);
t14 = l3.*t13;
t15 = t12+t14;
t16 = dthk.*t15;
t17 = dtha.*lc4.*t9;
t18 = dy-t16+t17;
t19 = lc3.^2;
t20 = dy-dthk.*lc3.*t13;
t26 = dthk.*lc4.*t3;
t22 = t21-t26;
t27 = dthk.*lc4.*t9;
t23 = t17-t27;
t24 = lc4.*t3.*t18.*2.0;
t25 = t16-t17;
t28 = lc4.*t9.*t11.*2.0;
b = [Fy-g.*m1-g.*m2-g.*m3-g.*m4-dthk.*(m4.*(dthk.*t8.*2.0-dtha.*lc4.*t3.*2.0).*(1.0./2.0)+dthk.*lc3.*m3.*t5)-dtha.*m4.*(dtha.*lc4.*t3.*2.0-dthk.*lc4.*t3.*2.0).*(1.0./2.0);tauk-Fy.*(t14+l4.*t9)+m4.*(t11.*t18.*2.0+t11.*(t16-dtha.*lc4.*t9).*2.0).*(1.0./2.0)+m3.*(dthk.*lc3.*t5.*t20.*2.0+dthk.^2.*t5.*t13.*t19.*2.0).*(1.0./2.0)-dthk.*(m4.*(t8.*t18.*2.0+t8.*t25.*2.0).*(1.0./2.0)+m3.*(lc3.*t5.*t20.*2.0+dthk.*t5.*t13.*t19.*2.0).*(1.0./2.0))+dtha.*m4.*(t24+t28-t8.*t23.*2.0+t15.*t22.*2.0).*(1.0./2.0)+g.*m4.*t15+g.*lc3.*m3.*t13;taua+m4.*(t11.*t23.*2.0+t18.*t22.*2.0).*(1.0./2.0)+Fy.*l4.*t9+dthk.*m4.*(t24+lc4.*t3.*t25.*2.0).*(1.0./2.0)-dtha.*m4.*(t24+t28-lc4.*t3.*t23.*2.0+lc4.*t9.*t22.*2.0).*(1.0./2.0)-g.*lc4.*m4.*t9];
