function COM = COM_GRAC_leg(in1,in2)
%COM_GRAC_LEG
%    COM = COM_GRAC_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Nov-2019 13:01:31

COM = [0.0;0.0];
