function dC = dC_GRAC_leg(in1,in2,in3)
%DC_GRAC_LEG
%    DC = DC_GRAC_LEG(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Nov-2019 13:01:31

dy = in1(4,:);
dC = dy;
