function A = A_GRAC_leg(in1,in2)
%A_GRAC_LEG
%    A = A_GRAC_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-Nov-2019 18:59:18

I3 = in2(8,:);
I4 = in2(10,:);
l3 = in2(13,:);
lc3 = in2(16,:);
lc4 = in2(17,:);
m1 = in2(3,:);
m2 = in2(5,:);
m3 = in2(7,:);
m4 = in2(9,:);
tha = in1(3,:);
thh = in2(2,:);
thk = in1(2,:);
t2 = thh-thk;
t3 = sin(t2);
t4 = tha+thh-thk;
t5 = sin(t4);
t6 = lc4.*t5.*2.0;
t7 = l3.*t3.*2.0;
t8 = t6+t7;
t9 = m4.*t8.*(-1.0./2.0)-lc3.*m3.*t3;
t10 = cos(t2);
t11 = lc3.^2;
t17 = lc4.*t5;
t18 = l3.*t3;
t12 = t17+t18;
t14 = cos(t4);
t15 = lc4.*t14;
t16 = l3.*t10;
t13 = t15+t16;
t19 = lc4.*m4.*t5;
t20 = lc4.*t13.*t14.*2.0;
t21 = lc4.*t5.*t12.*2.0;
t22 = t20+t21;
t23 = lc4.^2;
A = reshape([m1+m2+m3+m4,t9,t19,t9,I3+m3.*(t3.^2.*t11.*2.0+t10.^2.*t11.*2.0).*(1.0./2.0)+m4.*(t12.^2.*2.0+t13.^2.*2.0).*(1.0./2.0),m4.*t22.*(-1.0./2.0),t19,m4.*t22.*(-1.0./2.0),I4+m4.*(t5.^2.*t23.*2.0+t14.^2.*t23.*2.0).*(1.0./2.0)],[3,3]);
