function COM = COM_GRAC_leg(in1,in2)
%COM_GRAC_LEG
%    COM = COM_GRAC_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    18-Nov-2019 13:49:21

dy = in1(4,:);
y = in1(1,:);
COM = [y;dy];
