function E = energy_GRAC_leg(in1,in2)
%ENERGY_GRAC_LEG
%    E = ENERGY_GRAC_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    18-Nov-2019 13:49:18

I3 = in2(8,:);
I4 = in2(10,:);
dtha = in1(6,:);
dthk = in1(5,:);
dy = in1(4,:);
g = in2(19,:);
l2 = in2(12,:);
l3 = in2(13,:);
lc2 = in2(15,:);
lc3 = in2(16,:);
lc4 = in2(17,:);
lh0 = in2(18,:);
m1 = in2(3,:);
m2 = in2(5,:);
m3 = in2(7,:);
m4 = in2(9,:);
tha = in1(3,:);
thh = in2(2,:);
thh0 = in2(1,:);
thk = in1(2,:);
y = in1(1,:);
t2 = cos(thh);
t3 = cos(thh0);
t4 = dthk.^2;
t5 = dy.^2;
t8 = -thk;
t9 = -y;
t6 = l2.*t2;
t7 = lh0.*t3;
t10 = t8+thh;
t11 = cos(t10);
t12 = sin(t10);
t13 = t10+tha;
t14 = cos(t13);
t15 = sin(t13);
t16 = l3.*t11;
t17 = lc4.*t14;
E = (I3.*t4)./2.0+(m1.*t5)./2.0+(m2.*t5)./2.0+(m3.*((dy-dthk.*lc3.*t12).^2+lc3.^2.*t4.*t11.^2))./2.0+(I4.*dtha.^2)./2.0+(m4.*((dthk.*(t16+t17)-dtha.*t17).^2+(dy-dthk.*(l3.*t12+lc4.*t15)+dtha.*lc4.*t15).^2))./2.0-g.*m3.*(t6+t7+t9+lc3.*t11)+g.*m1.*y-g.*m2.*(t7+t9+lc2.*t2)-g.*m4.*(t6+t7+t9+t16+t17);
