function Jleg = jacobian_foot(in1,in2)
%JACOBIAN_FOOT
%    JLEG = JACOBIAN_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    18-Nov-2019 13:49:22

l3 = in2(13,:);
l4 = in2(14,:);
tha = in1(3,:);
thh = in2(2,:);
thk = in1(2,:);
t2 = -thk;
t3 = t2+thh;
t4 = t3+tha;
t5 = cos(t4);
t6 = sin(t4);
t7 = l4.*t5;
t8 = l4.*t6;
Jleg = reshape([0.0,1.0,0.0,-t7-l3.*cos(t3),-t8-l3.*sin(t3),0.0,t7,t8,0.0],[3,3]);
