function dre = velocity_foot(in1,in2)
%VELOCITY_FOOT
%    DRE = VELOCITY_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Nov-2019 15:56:28

dtha = in1(6,:);
dthk = in1(5,:);
dy = in1(4,:);
l3 = in2(13,:);
l4 = in2(14,:);
tha = in1(3,:);
thh = in2(2,:);
thk = in1(2,:);
t2 = -thk;
t3 = t2+thh;
t4 = t3+tha;
t5 = cos(t4);
t6 = sin(t4);
dre = [-dthk.*(l4.*t5+l3.*cos(t3))+dtha.*l4.*t5;dy-dthk.*(l4.*t6+l3.*sin(t3))+dtha.*l4.*t6;0.0];
