function Jleg = jacobian_foot(in1,in2)
%JACOBIAN_FOOT
%    JLEG = JACOBIAN_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Nov-2019 13:23:19

l3 = in2(13,:);
thh = in2(2,:);
thk = in1(2,:);
t2 = -thk;
t3 = t2+thh;
Jleg = reshape([0.0,1.0,0.0,-l3.*cos(t3),-l3.*sin(t3),0.0],[3,2]);
