function A = kA_GRAC_leg(in1,in2)
%KA_GRAC_LEG
%    A = KA_GRAC_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Nov-2019 15:13:54

I3 = in2(8,:);
lc3 = in2(16,:);
m1 = in2(3,:);
m2 = in2(5,:);
m3 = in2(7,:);
thh = in2(2,:);
thk = in1(2,:);
t2 = lc3.^2;
t3 = -thk;
t4 = t3+thh;
t5 = sin(t4);
t6 = lc3.*m3.*t5;
t7 = -t6;
A = reshape([m1+m2+m3,t7,t7,I3+(m3.*(t2.*cos(t4).^2.*2.0+t2.*t5.^2.*2.0))./2.0],[2,2]);
