function b = kb_GRAC_leg(in1,tauk,Fy,in4)
%KB_GRAC_LEG
%    B = KB_GRAC_LEG(IN1,TAUK,FY,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Nov-2019 13:29:56

dthk = in1(4,:);
dy = in1(3,:);
g = in4(19,:);
l3 = in4(13,:);
lc3 = in4(16,:);
m1 = in4(3,:);
m2 = in4(5,:);
m3 = in4(7,:);
thh = in4(2,:);
thk = in1(2,:);
t2 = dthk.^2;
t3 = lc3.^2;
t4 = -thk;
t5 = t4+thh;
t6 = cos(t5);
t7 = sin(t5);
t8 = dthk.*lc3.*t7;
t9 = -t8;
t10 = dy+t9;
b = [Fy-g.*m1-g.*m2-g.*m3-lc3.*m3.*t2.*t6;tauk+(m3.*(dthk.*lc3.*t6.*t10.*2.0+t2.*t3.*t6.*t7.*2.0))./2.0-(dthk.*m3.*(lc3.*t6.*t10.*2.0+dthk.*t3.*t6.*t7.*2.0))./2.0-Fy.*l3.*t7+g.*lc3.*m3.*t7];
