function C = kC_GRAC_leg(in1,tauk,in3)
%KC_GRAC_LEG
%    C = KC_GRAC_LEG(IN1,TAUK,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Nov-2019 15:51:29

y = in1(1,:);
C = y;
