function dC = kdC_GRAC_leg(in1,tauk,in3)
%KDC_GRAC_LEG
%    DC = KDC_GRAC_LEG(IN1,TAUK,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Nov-2019 13:29:57

dy = in1(3,:);
dC = dy;
