function E = energy_GRAC_leg(in1,in2)
%ENERGY_GRAC_LEG
%    E = ENERGY_GRAC_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    08-Nov-2019 14:30:36

I3 = in2(8,:);
I4 = in2(10,:);
dtha = in1(6,:);
dthk = in1(5,:);
dy = in1(4,:);
g = in2(19,:);
l2 = in2(12,:);
l3 = in2(13,:);
lc2 = in2(15,:);
lc3 = in2(16,:);
lc4 = in2(17,:);
lh0 = in2(18,:);
m1 = in2(3,:);
m2 = in2(5,:);
m3 = in2(7,:);
m4 = in2(9,:);
tha = in1(3,:);
thh = in2(2,:);
thh0 = in2(1,:);
thk = in1(2,:);
y = in1(1,:);
t2 = tha+thh-thk;
t3 = sin(t2);
t5 = thh-thk;
t9 = sin(t5);
t4 = dy-dthk.*(l3.*t9+lc4.*t3)+dtha.*lc4.*t3;
t6 = cos(t2);
t12 = cos(t5);
t16 = lc4.*t6;
t18 = l3.*t12;
t7 = dthk.*(t16+t18)-dtha.*lc4.*t6;
t8 = dy.^2;
t10 = dy-dthk.*lc3.*t9;
t11 = dthk.^2;
t13 = cos(thh);
t14 = cos(thh0);
t15 = lh0.*t14;
t17 = l2.*t13;
E = I3.*t11.*(1.0./2.0)+m1.*t8.*(1.0./2.0)+m2.*t8.*(1.0./2.0)+I4.*dtha.^2.*(1.0./2.0)+m3.*(t10.^2+lc3.^2.*t11.*t12.^2).*(1.0./2.0)+m4.*(t4.^2+t7.^2).*(1.0./2.0)-g.*m2.*(t15-y+lc2.*t13)-g.*m4.*(t15+t16+t17+t18-y)-g.*m3.*(t15+t17-y+lc3.*t12)+g.*m1.*y;
