function Jleg = jacobian_foot(in1,in2)
%JACOBIAN_FOOT
%    JLEG = JACOBIAN_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    08-Nov-2019 14:30:38

l3 = in2(13,:);
l4 = in2(14,:);
tha = in1(3,:);
thh = in2(2,:);
thk = in1(2,:);
t2 = tha+thh-thk;
t3 = cos(t2);
t4 = thh-thk;
t5 = sin(t2);
Jleg = reshape([0.0,1.0,0.0,-l4.*t3-l3.*cos(t4),-l4.*t5-l3.*sin(t4),0.0,l4.*t3,l4.*t5,0.0],[3,3]);
