function dC = dC_GRAC_leg(in1,tauk,in3)
%DC_GRAC_LEG
%    DC = DC_GRAC_LEG(IN1,TAUK,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Nov-2019 13:23:18

dy = in1(3,:);
dC = dy;
