function COM = kCOM_GRAC_leg(in1,in2)
%KCOM_GRAC_LEG
%    COM = KCOM_GRAC_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Nov-2019 13:29:57

dy = in1(3,:);
y = in1(1,:);
COM = [y;dy];
